apiVersion: 1                                                   
                                                        
# list of datasources that should be deleted from the database
deleteDatasources:                               
- name: SenitmentAnalysis                                    
  orgId: 1                                                 
                                                  
# list of datasources to insert/update depending        
# on what's available in the database                          
datasources:                                                   
# <string, required> name of the datasource. Required   
- name: SenitmentAnalysis                                 
#   # <string, required> datasource type. Required             
  type: influxdb                                    
#   # <string, required> access mode. direct or proxy. Required
  access: proxy                                         
# <int> org id. will default to orgId 1 if not specified                 
  orgId: 1                                                               
#   # <string> url                   
  url: http://influxdb:8086                             
# <string> database password, if used               
  password: "CHANGEME"                                                   
#   # <string> database user, if used                     
  user: "NH"                                              
#   # <string> database name, if used                                    
  database: "influxSentiment"                           
#   # <bool> enable/disable basic auth              
#  basicAuth: false                                                        
#   # <string> basic auth username                      
#  basicAuthUser: admin                                  
# <string> basic auth password
#  basicAuthPassword: admin                              
#   # <bool> enable/disable with credentials headers           
#   withCredentials:                                
#   # <bool> mark as default datasource. Max one per org       
#   isDefault:                                          
#   # <map> fields that will be converted to json and stored in json_data
  jsonData:
    httpMode: GET                                                            
#      graphiteVersion: "1.1"                           
#      tlsAuth: true                                    
#      tlsAuthWithCACert: true                                           
#      httpHeaderName1: "Authorization"                                  
#   # <string> json object of data that will be encrypted.
#   secureJsonData:                                       
#     tlsCACert: "..."                                                   
#     tlsClientCert: "..."                              
#     tlsClientKey: "..."                                 
#     # <openshift\kubernetes token example>                             
#     httpHeaderValue1: "Bearer xf5yhfkpsnmgo"          
#   version: 1                                          
#   # <bool> allow users to edit datasources from the UI. 